version: 0.2 

phases:
  install:
    runtime-versions:
      java: corretto8
      
    commands:
      - mvn package
      - sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket vnsny-ci-cd-pipeline-bucket
      - sam deploy --template-file packaged.yaml --stack-name sam-orderHandler --capabilities CAPABILITY_IAM --parameter-overrides MyParameterSample=MySampleValue 
      - aws cloudformation describe-stacks --stack-name sam-orderHandler --query 'Stacks[].Outputs' 
      
artifacts: 
  type: zip 
  files:
    - template.yaml
    - packaged.yaml
    
